parameters:
  - name: npmUserConfig
    type: string
    default: '/home/kwazdo/.npmrc'

  - name: projectPath
    type: string
    default: '/'

  - name: artifactPath
    type: object
    default:
      - 'target/'

  - name: npmBuildCmd
    type: object
    default:
      - 'run build'

  - name: publishBuildArtifacts
    type: boolean
    default: false

  - name: retention
    type: boolean
    default: true

  - name: releaseRegistryUrl
    type: string
    default: "https://spu.sha.vrkw.de/nexus/repository/npm-releases/"

  - name: snapshotRegistryUrl
    type: string
    default: "https://spu.sha.vrkw.de/nexus/repository/npm-releases/"

  - name: tagRelease
    type: boolean
    default: true

  - name: agentPoolName
    type: string
    default: "Self-hosted Linux (SEU)"

  - name: timeoutInMinutes
    type: number
    default: 30

jobs:
  - job: build_default_branch_job
    condition: |
      or(
        eq(variables['Build.SourceBranch'], 'refs/heads/master'),
        eq(variables['Build.SourceBranch'], 'refs/heads/main'),
        eq(variables['Build.SourceBranch'], 'refs/heads/develop')
      )
    displayName: Default-Branch bauen
    timeoutInMinutes: ${{ parameters.timeoutInMinutes }}
    pool:
      name: ${{ parameters.agentPoolName }}
    variables:
      branchRunCounter: $[ counter(variables['Build.SourceBranchName'], 1) ]
    steps:
      - template: templates/stepsPrepare.yml
        parameters:
          projectPath: ${{ parameters.projectPath }}
          npmUserConfig: ${{ parameters.npmUserConfig }}

      - template: templates/stepsValidateDefaultBranch.yml
        parameters:
          projectPath: ${{ parameters.projectPath }}

      - template: templates/stepsNpmBuildPublish.yml
        parameters:
          projectPath: ${{ parameters.projectPath }}
          npmBuildCmd: ${{ parameters.npmBuildCmd }}
          npmUserConfig: ${{ parameters.npmUserConfig }}
          artifactPath: ${{ parameters.artifactPath }}
          publishBuildArtifacts: ${{ parameters.publishBuildArtifacts }}
          retention: ${{ parameters.retention }}
          publishRegistry: ${{ parameters.snapshotRegistryUrl }}
          publishTag: '$(versionLabel)'
          publishNpm: true

  - job: build_release_branch_job
    condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')
    displayName: Release-Branch bauen
    timeoutInMinutes: ${{ parameters.timeoutInMinutes }}
    pool:
      name: ${{ parameters.agentPoolName }}
    variables:
      branchRunCounter: $[ counter(variables['Build.SourceBranchName'], 1) ]
    steps:
      - template: templates/stepsPrepare.yml
        parameters:
          projectPath: ${{ parameters.projectPath }}
          npmUserConfig: ${{ parameters.npmUserConfig }}

      - template: templates/stepsValidateReleaseBranch.yml
        parameters:
          projectPath: ${{ parameters.projectPath }}

      - template: templates/stepsNpmBuildPublish.yml
        parameters:
          projectPath: ${{ parameters.projectPath }}
          npmBuildCmd: ${{ parameters.npmBuildCmd }}
          npmUserConfig: ${{ parameters.npmUserConfig }}
          artifactPath: ${{ parameters.artifactPath }}
          publishBuildArtifacts: ${{ parameters.publishBuildArtifacts }}
          retention: ${{ parameters.retention }}
          publishRegistry: ${{ parameters.releaseRegistryUrl }}
          publishTag: 'release-$(majorMinor)'
          publishNpm: true
          tagRelease: ${{ parameters.tagRelease }}

  - job: build_other_branch_job
    condition: |
      and(
        not(
          or(
            eq(variables['Build.SourceBranch'], 'refs/heads/master'),
            eq(variables['Build.SourceBranch'], 'refs/heads/main'),
            eq(variables['Build.SourceBranch'], 'refs/heads/develop')
          )
        ),
        not(startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'))
      )
    displayName: Sonstigen Branch bauen
    timeoutInMinutes: ${{ parameters.timeoutInMinutes }}
    pool:
      name: ${{ parameters.agentPoolName }}
    variables:
      branchRunCounter: $[ counter(variables['Build.SourceBranchName'], 1) ]
    steps:
      - template: templates/stepsPrepare.yml
        parameters:
          projectPath: ${{ parameters.projectPath }}
          npmUserConfig: ${{ parameters.npmUserConfig }}

      - template: templates/stepsNpmBuildPublish.yml
        parameters:
          projectPath: ${{ parameters.projectPath }}
          npmBuildCmd: ${{ parameters.npmBuildCmd }}
          npmUserConfig: ${{ parameters.npmUserConfig }}
          artifactPath: ${{ parameters.artifactPath }}
          publishBuildArtifacts: false
          publishNpm: false
