parameters:
  - name: jobName
    type: string

  - name: displayName
    type: string

  - name: branchType
    type: string
    values:
      - default
      - release
      - other

  - name: validationTemplate
    type: string
    default: ''

  - name: workspacePath
    type: string

  - name: packagePath
    type: string

  - name: publishPath
    type: string

  - name: npmUserConfig
    type: string

  - name: artifactPath
    type: object

  - name: buildCommands
    type: object

  - name: publishBuildArtifacts
    type: boolean

  - name: retentionDays
    type: number

  - name: publishRegistry
    type: string
    default: ''

  - name: publishTag
    type: string
    default: ''

  - name: publishNpm
    type: boolean
    default: true

  - name: tagRelease
    type: boolean
    default: false

  - name: gitTagTemplate
    type: string
    default: '$(releaseNumber)'

  - name: agentPoolName
    type: string

  - name: poolRequirements
    type: object

  - name: timeoutInMinutes
    type: number

jobs:
  - template: jobsPackageBuild.yml
    parameters:
      jobName: ${{ parameters.jobName }}
      displayName: ${{ parameters.displayName }}
      branchType: ${{ parameters.branchType }}
      validationTemplate: ${{ parameters.validationTemplate }}
      workspacePath: ${{ parameters.workspacePath }}
      packagePath: ${{ parameters.packagePath }}
      publishPath: ${{ parameters.publishPath }}
      npmUserConfig: ${{ parameters.npmUserConfig }}
      artifactPath: ${{ parameters.artifactPath }}
      buildCommands: ${{ parameters.buildCommands }}
      publishBuildArtifacts: ${{ parameters.publishBuildArtifacts }}
      retentionDays: ${{ parameters.retentionDays }}
      publishRegistry: ${{ parameters.publishRegistry }}
      publishTag: ${{ parameters.publishTag }}
      publishNpm: ${{ parameters.publishNpm }}
      tagRelease: ${{ parameters.tagRelease }}
      gitTagTemplate: ${{ parameters.gitTagTemplate }}
      agentPoolName: ${{ parameters.agentPoolName }}
      poolRequirements: ${{ parameters.poolRequirements }}
      timeoutInMinutes: ${{ parameters.timeoutInMinutes }}
