parameters:
  - name: jobName
    type: string

  - name: displayName
    type: string

  - name: branchType
    type: string
    values:
      - default
      - release
      - other

  - name: validationTemplate
    type: string
    default: ''

  - name: workspacePath
    type: string

  - name: packagePath
    type: string

  - name: publishPath
    type: string

  - name: npmUserConfig
    type: string

  - name: artifactPath
    type: object

  - name: npmBuildCmd
    type: object
    default: []

  - name: buildCommands
    type: object
    default: []

  - name: publishBuildArtifacts
    type: boolean

  - name: retentionDays
    type: number

  - name: publishRegistry
    type: string
    default: ''

  - name: publishTag
    type: string
    default: ''

  - name: publishNpm
    type: boolean
    default: true

  - name: tagRelease
    type: boolean
    default: false

  - name: gitTagTemplate
    type: string
    default: '$(releaseNumber)'

  - name: agentPoolName
    type: string

  - name: poolRequirements
    type: object

  - name: timeoutInMinutes
    type: number

jobs:
  - job: ${{ parameters.jobName }}
    dependsOn: resolve_default_branch
    displayName: ${{ parameters.displayName }}
    ${{ if eq(parameters.branchType, 'default') }}:
      condition: |
        and(
          succeeded(),
          eq(dependencies.resolve_default_branch.outputs['resolveDefaultBranch.isDefaultBranch'], 'true')
        )
    ${{ if eq(parameters.branchType, 'release') }}:
      condition: |
        and(
          succeeded(),
          ne(dependencies.resolve_default_branch.outputs['resolveDefaultBranch.isDefaultBranch'], 'true'),
          eq(variables['isReleaseBranch'], 'true')
        )
    ${{ if eq(parameters.branchType, 'other') }}:
      condition: |
        and(
          succeeded(),
          ne(dependencies.resolve_default_branch.outputs['resolveDefaultBranch.isDefaultBranch'], 'true'),
          ne(variables['isReleaseBranch'], 'true')
        )
    timeoutInMinutes: ${{ parameters.timeoutInMinutes }}
    pool:
      name: ${{ parameters.agentPoolName }}
      demands:
        - ${{ each poolRequirement in parameters.poolRequirements }}:
            - ${{ poolRequirement }}
    variables:
      - template: ../../variables/ReleaseVariablesTmpl.yml
      - name: branchRunCounter
        value: $[ counter(variables['Build.SourceBranchName'], 1) ]
      - name: defaultBranchRef
        value: $[ dependencies.resolve_default_branch.outputs['resolveDefaultBranch.defaultBranchRef'] ]
      - name: isDefaultBranch
        value: $[ dependencies.resolve_default_branch.outputs['resolveDefaultBranch.isDefaultBranch'] ]
    steps:
      - template: stepsPrepare.yml
        parameters:
          workspacePath: ${{ parameters.workspacePath }}
          packagePath: ${{ parameters.packagePath }}
          publishPath: ${{ parameters.publishPath }}

      - ${{ if ne(parameters.validationTemplate, '') }}:
          - template: ${{ parameters.validationTemplate }}

      - template: stepsNpmBuildPublish.yml
        parameters:
          npmBuildCmd: ${{ parameters.npmBuildCmd }}
          buildCommands: ${{ parameters.buildCommands }}
          npmUserConfig: ${{ parameters.npmUserConfig }}
          artifactPath: ${{ parameters.artifactPath }}
          publishBuildArtifacts: ${{ parameters.publishBuildArtifacts }}
          retentionDays: ${{ parameters.retentionDays }}
          publishRegistry: ${{ parameters.publishRegistry }}
          publishTag: ${{ parameters.publishTag }}
          publishNpm: ${{ parameters.publishNpm }}
          tagRelease: ${{ parameters.tagRelease }}
          gitTagTemplate: ${{ parameters.gitTagTemplate }}
